### PR TITLE
Different

### PR DESCRIPTION
**Pull request by MangyCoyote**
Lemme know what you think.

I am aware of missing doc atm - I like Preview feature at GitHub.

Actually, we might want to have this behavior enabled by default (perhaps in next phase). I realized as we "speak" now.

### CODE REVIEW

**Comment by iricigor** [comment]
This needs some brainstorming. I am thinking about performance impacts. What if we add some simple test before hash check, like file/blob size matching?

**Comment by MangyCoyote** [comment]
I tried on 3 tiny files (included just some line with randomized string) on **_our VM (size)_**. It is comparable. See below.
It may be also possibly faster for setblob. Depends on user scenarios.

```
$ cat Upload/
a  b  c/ d  
$ cat Upload/a 
Echooooo
c
$ cat Upload/b 
Achooooj
$ cat Upload/c/tse 
Je moucha
$ cat Upload/d 
d
```

```
$ time ./azmi setblobs --container https://x.blob.core.windows.net/y --directory ./Upload/ --force
Success 'https://x.blob.core.windows.net/y/a'
Success 'https://x.blob.core.windows.net/y/b'
Success 'https://x.blob.core.windows.net/y/d'
Success 'https://x.blob.core.windows.net/y/c%2Ftse' <-- btw note this encoding

real	0m4.569s
user	0m2.937s
sys	0m0.474s
```

The same but with --skip-if-same flag enabled = all 4 ^^ blobs skipped:
```
real	0m4.593s
user	0m2.847s
sys	0m0.465s
```

Second scenario (attempt to upload tiny single file):
```
$ time ./azmi setblobs --container https://x.blob.core.windows.net/z --directory ./Upload/c/ --force
Success 'https://x.blob.core.windows.net/z/tse'

real	0m4.282s
user	0m2.766s
sys	0m0.520s
$ time ./azmi setblobs --container https://x.blob.core.windows.net/z --directory ./Upload/c/ --force --skip-if-same
File '/home/me/Upload/c/tse' and blob 'https://x.blob.core.windows.net/z/tse' are same. Skip setting the blob.

real	0m3.396s
user	0m2.889s
sys	0m0.475s
```

Maybe we can revert idea and use optional flag --write-even-if-hashes-are-same (also for setblob).
Try to test it yourself.

**Comment by iricigor** [comment]
I am thinking to add this in scope of performance tests. Something like:
- generate random files - [something like this](https://unix.stackexchange.com/a/33634/303029)
- measure normal upload
- measure re-upload with `--skip-if-same`
- re-generate the same random files with updated content
- measure upload with `--skip-if-same`

On last test, I am expecting it to be significantly slower. Foreach file, we are first downloading info about blob and then uploading the file as it is different.

**Comment by iricigor** [comment]
Performanbce summary from [the build run](https://dev.azure.com/iiric/azmi/_build/results?buildId=2321&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=c623b9f5-4e91-5154-177e-19d7203ddd0d)
```
just upload files: 10.278s
check and skip:     8.375s
check and upload:  12.781s
```

Two questions:
- What do you mean by: "I like Preview feature at GitHub"? 
- Lets open a ticket for adding documentation?

Otherwise, no comments, good job! 👍

**Pull request merged**
